import type { BusinessData, BusinessRepository } from './businessRepository.js';
import type { EdgeObservationRecord, Feedback, InventoryRecord, Product, ProductInput, Promotion, SaleInput, SaleItemRecord } from '../types/domain.js';
import { getPostgresPool, withPostgresTransaction, type PgRow } from '../database/postgresPool.js';

const number = (value: unknown) => Number(value ?? 0);
const makeId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const iso = (value: unknown) => new Date(String(value)).toISOString();

export class PostgresRepository implements BusinessRepository {
  public constructor(private readonly seed: BusinessData) { void seed; }
  public async read(): Promise<BusinessData> {
    const pool = getPostgresPool();
    const [products, sales, purchases, promotions, feedback, observations, items] = await Promise.all([
      pool.query<PgRow>('SELECT p.id,p.name,p.price,p.image_url,p.aisle,p.shelf,p.expiration_date,c.name AS category,i.digital_stock,i.physical_stock,i.reorder_point,i.average_sales,i.last_physical_observation_at,i.aruco_id FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN inventory i ON i.product_id=p.id ORDER BY p.created_at,p.id'),
      pool.query<PgRow>('SELECT s.id,s.subtotal,s.discount_total,s.payment_method,s.created_at,SUM(si.quantity) AS quantity,MIN(si.product_id) AS product_id,MIN(p.name) AS product_name,MIN(si.unit_price) AS unit_price,json_agg(json_build_object(\'id\',si.id,\'productId\',si.product_id,\'productName\',p.name,\'quantity\',si.quantity,\'unitPrice\',si.unit_price,\'discount\',si.discount,\'subtotal\',si.subtotal) ORDER BY si.id) AS items FROM sales s JOIN sale_items si ON si.sale_id=s.id JOIN products p ON p.id=si.product_id GROUP BY s.id ORDER BY s.created_at DESC'),
      pool.query<PgRow>('SELECT pu.id,pi.product_id,p.name AS product_name,pi.quantity,pu.created_at FROM purchases pu JOIN purchase_items pi ON pi.purchase_id=pu.id JOIN products p ON p.id=pi.product_id ORDER BY pu.created_at DESC'),
      pool.query<PgRow>('SELECT id,title,description,image_url,active FROM promotions ORDER BY created_at,id'),
      pool.query<PgRow>('SELECT id,mood,comment,created_at FROM feedback ORDER BY created_at'),
      pool.query<PgRow>('SELECT id,observation_id,zone_id,source_id,observed_at FROM edge_observations ORDER BY observed_at'),
      pool.query<PgRow>('SELECT edge_observation_id,product_id,quantity FROM edge_observation_items ORDER BY id'),
    ]);
    const productRows: Product[] = products.rows.map((row) => ({ id: String(row.id), name: String(row.name), category: String(row.category), price: number(row.price), stock: number(row.digital_stock), ...(row.image_url ? { imageUrl: String(row.image_url) } : {}), ...(row.aisle ? { aisle: String(row.aisle) } : {}), ...(row.shelf ? { shelf: String(row.shelf) } : {}), ...(row.expiration_date ? { expirationDate: String(row.expiration_date).slice(0, 10) } : {}) }));
    const inventory: InventoryRecord[] = products.rows.map((row) => ({ id: String(row.id), name: String(row.name), category: String(row.category), price: number(row.price), ...(row.image_url ? { imageUrl: String(row.image_url) } : {}), ...(row.aisle ? { aisle: String(row.aisle) } : {}), ...(row.shelf ? { shelf: String(row.shelf) } : {}), digitalStock: number(row.digital_stock), ...(row.expiration_date ? { expirationDate: String(row.expiration_date).slice(0, 10) } : {}), physicalStock: number(row.physical_stock), reorderPoint: number(row.reorder_point), averageSales: number(row.average_sales), ...(row.last_physical_observation_at ? { observedAt: iso(row.last_physical_observation_at) } : {}), ...(row.aruco_id !== null && row.aruco_id !== undefined ? { arucoId: number(row.aruco_id) } : {}) }));
    const edgeObservations = observations.rows.map((row) => ({ observationId: String(row.observation_id), zoneId: String(row.zone_id), sourceId: String(row.source_id), observedAt: iso(row.observed_at), items: items.rows.filter((item) => String(item.edge_observation_id) === String(row.id)).map((item) => ({ productId: String(item.product_id), quantity: number(item.quantity) })) }));
    return { products: productRows, inventory, sales: sales.rows.map((row) => { const items = (Array.isArray(row.items) ? row.items : []) as SaleItemRecord[]; return { id: String(row.id), productId: String(row.product_id), productName: String(row.product_name), quantity: number(row.quantity), unitPrice: number(row.unit_price), createdAt: iso(row.created_at), items, subtotal: number(row.subtotal), discountTotal: number(row.discount_total), total: number(row.subtotal) - number(row.discount_total), paymentMethod: String(row.payment_method ?? 'cash') as 'cash' | 'card' | 'transfer' }; } ), purchases: purchases.rows.map((row) => ({ id: String(row.id), productId: String(row.product_id), productName: String(row.product_name), quantity: number(row.quantity), createdAt: iso(row.created_at) })), promotions: promotions.rows.map((row) => ({ id: String(row.id), title: String(row.title), description: String(row.description), imageUrl: row.image_url ? String(row.image_url) : undefined, active: Boolean(row.active) })), feedback: feedback.rows.map((row) => ({ id: String(row.id), mood: String(row.mood) as Feedback['mood'], comment: String(row.comment ?? ''), createdAt: iso(row.created_at) })), processedObservationIds: edgeObservations.map((item) => item.observationId), edgeObservations };
  }
  public async createProduct(product: ProductInput) { return withPostgresTransaction(async (client) => { const categoryId = `category-${product.category.toLocaleLowerCase().trim().replace(/[^a-z0-9]+/g, '-')}`; await client.query('INSERT INTO categories (id,name,slug) VALUES ($1,$2,$3) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name', [categoryId, product.category, categoryId]); await client.query('INSERT INTO products (id,category_id,name,normalized_name,price,image_url,aisle,shelf,expiration_date,active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,TRUE)', [product.id, categoryId, product.name, product.name.toLocaleLowerCase().trim().replace(/\s+/g, ' '), product.price, product.imageUrl ?? null, product.aisle ?? null, product.shelf ?? null, product.expirationDate ?? null]); await client.query('INSERT INTO inventory (product_id,digital_stock,physical_stock,reorder_point,average_sales) VALUES ($1,$2,$3,$4,$5)', [product.id, product.stock, product.stock, product.reorderPoint, 0]); return { id: product.id, name: product.name, category: product.category, price: product.price, stock: product.stock, ...(product.imageUrl ? { imageUrl: product.imageUrl } : {}), ...(product.aisle ? { aisle: product.aisle } : {}), ...(product.shelf ? { shelf: product.shelf } : {}), ...(product.expirationDate ? { expirationDate: product.expirationDate } : {}) }; }); }
  public async updateProduct(productId: string, product: ProductInput) { return withPostgresTransaction(async (client) => { const categoryId = 'category-' + product.category.toLocaleLowerCase().trim().replace(/[^a-z0-9]+/g, '-'); await client.query('INSERT INTO categories (id,name,slug) VALUES ($1,$2,$3) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name', [categoryId, product.category, categoryId]); await client.query('UPDATE products SET category_id=$1,name=$2,normalized_name=$3,price=$4,image_url=$5,aisle=$6,shelf=$7,expiration_date=$8,updated_at=CURRENT_TIMESTAMP WHERE id=$9', [categoryId, product.name, product.name.toLocaleLowerCase().trim().replace(/\s+/g, ' '), product.price, product.imageUrl ?? null, product.aisle ?? null, product.shelf ?? null, product.expirationDate ?? null, productId]); await client.query('UPDATE inventory SET digital_stock=$1,physical_stock=$2,reorder_point=$3,updated_at=CURRENT_TIMESTAMP WHERE product_id=$4', [product.stock, product.stock, product.reorderPoint, productId]); return { id: productId, name: product.name, category: product.category, price: product.price, stock: product.stock, ...(product.imageUrl ? { imageUrl: product.imageUrl } : {}), ...(product.expirationDate ? { expirationDate: product.expirationDate } : {}) }; }); }
  public async updateInventory(productId: string, patch: Partial<InventoryRecord>) { await getPostgresPool().query('UPDATE inventory SET digital_stock=COALESCE($1,digital_stock),physical_stock=COALESCE($2,physical_stock),reorder_point=COALESCE($3,reorder_point),average_sales=COALESCE($4,average_sales),updated_at=CURRENT_TIMESTAMP WHERE product_id=$5', [patch.digitalStock ?? null, patch.physicalStock ?? null, patch.reorderPoint ?? null, patch.averageSales ?? null, productId]); return (await this.read()).inventory; }
  public async registerSale(input: SaleInput) { const paymentTable = await getPostgresPool().query<{ exists: boolean; canInsert: boolean }>("SELECT to_regclass('public.sale_payments') IS NOT NULL AS exists, has_table_privilege(current_user, 'public.sale_payments', 'INSERT') AS \"canInsert\""); const hasPaymentTable = Boolean(paymentTable.rows[0]?.exists && paymentTable.rows[0]?.canInsert); return withPostgresTransaction(async (client) => { const requestedItems = input.items ?? [{ productId: input.productId!, quantity: input.quantity! }]; const ids = requestedItems.map((item) => item.productId); const { rows } = await client.query<PgRow>('SELECT p.id,p.name,p.price,i.digital_stock FROM products p JOIN inventory i ON i.product_id=p.id WHERE p.id = ANY($1::text[]) FOR UPDATE OF i', [ids]); const products = new Map(rows.map((row) => [String(row.id), row])); const lineItems = requestedItems.map((item) => { const product = products.get(item.productId); if (!product) throw new Error(`Producto no encontrado: ${item.productId}.`); if (number(product.digital_stock) < item.quantity) throw new Error(`La cantidad de ${String(product.name)} supera el inventario disponible.`); const subtotal = item.quantity * number(product.price); return { productId: item.productId, productName: String(product.name), quantity: item.quantity, unitPrice: number(product.price), discount: 0, subtotal }; }); const subtotal = lineItems.reduce((sum, item) => sum + item.subtotal, 0); const discountTotal = input.discountTotal ?? 0; const total = subtotal - discountTotal; const id = makeId('sale'); const createdAt = new Date(); await client.query('INSERT INTO sales (id,created_at,subtotal,discount_total,total,payment_method,status) VALUES ($1,$2,$3,$4,$5,$6,$7)', [id, createdAt, subtotal, discountTotal, total, input.paymentMethod ?? 'cash', 'completed']); for (const item of lineItems) { await client.query('INSERT INTO sale_items (id,sale_id,product_id,quantity,unit_price,discount,subtotal) VALUES ($1,$2,$3,$4,$5,$6,$7)', [`${id}-${item.productId}`, id, item.productId, item.quantity, item.unitPrice, item.discount, item.subtotal]); await client.query('UPDATE inventory SET digital_stock=digital_stock-$1 WHERE product_id=$2', [item.quantity, item.productId]); } if (hasPaymentTable) await client.query('INSERT INTO sale_payments (id,sale_id,method,amount) VALUES ($1,$2,$3,$4)', [`${id}-payment`, id, input.paymentMethod ?? 'cash', total]); return { id, productId: lineItems[0].productId, productName: lineItems[0].productName, quantity: lineItems[0].quantity, unitPrice: lineItems[0].unitPrice, createdAt: createdAt.toISOString(), items: lineItems, subtotal, discountTotal, total, paymentMethod: input.paymentMethod ?? 'cash' as const }; }); }
  public async registerPurchase(productId: string, quantity: number) { return withPostgresTransaction(async (client) => { const { rows } = await client.query<PgRow>('SELECT p.name FROM products p JOIN inventory i ON i.product_id=p.id WHERE p.id=$1 FOR UPDATE OF i', [productId]); if (!rows[0]) throw new Error('Producto no encontrado.'); const id = makeId('purchase'); const createdAt = new Date(); await client.query('INSERT INTO purchases (id,created_at) VALUES ($1,$2)', [id, createdAt]); await client.query('INSERT INTO purchase_items (id,purchase_id,product_id,quantity) VALUES ($1,$2,$3,$4)', [`${id}-item`, id, productId, quantity]); await client.query('UPDATE inventory SET digital_stock=digital_stock+$1 WHERE product_id=$2', [quantity, productId]); return { id, productId, productName: String(rows[0].name), quantity, createdAt: createdAt.toISOString() }; }); }
  public async createPromotion(promotion: Promotion) { await getPostgresPool().query('INSERT INTO promotions (id,title,description,image_url,active) VALUES ($1,$2,$3,$4,$5)', [promotion.id, promotion.title, promotion.description, promotion.imageUrl ?? null, promotion.active]); return promotion; }
  public async updatePromotion(id: string, patch: Partial<Promotion>) { const current = (await this.read()).promotions.find((item) => item.id === id); if (!current) throw new Error('Promoción no encontrada.'); const next = { ...current, ...patch, id }; await getPostgresPool().query('UPDATE promotions SET title=$1,description=$2,image_url=$3,active=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$5', [next.title, next.description, next.imageUrl ?? null, next.active, id]); return next; }
  public async submitFeedback(feedback: Feedback) { await getPostgresPool().query("INSERT INTO feedback (id,mood,rating,comment,created_at) VALUES ($1,$2,$3,$4,$5)", [feedback.id, feedback.mood, feedback.mood === 'happy' ? 5 : feedback.mood === 'neutral' ? 3 : 1, feedback.comment, feedback.createdAt]); return feedback; }
  public async ingestObservation(observation: EdgeObservationRecord) { await withPostgresTransaction(async (client) => { const existing = await client.query<PgRow>("SELECT id FROM edge_observations WHERE observation_id=$1 FOR UPDATE", [observation.observationId]); if (existing.rows[0]) return; const result = await client.query<PgRow>("INSERT INTO edge_observations (observation_id,zone_id,source_id,observed_at) VALUES ($1,$2,$3,$4) RETURNING id", [observation.observationId, observation.zoneId, observation.sourceId, observation.observedAt]); const id = result.rows[0].id; for (const item of observation.items) { await client.query("INSERT INTO edge_observation_items (edge_observation_id,product_id,quantity) VALUES ($1,$2,$3)", [id, item.productId, item.quantity]); await client.query("UPDATE inventory SET physical_stock=$1,last_physical_observation_at=$2,updated_at=CURRENT_TIMESTAMP WHERE product_id=$3", [item.quantity, observation.observedAt, item.productId]); } }); return this.read(); }
  public async replace(data: BusinessData): Promise<void> { await withPostgresTransaction(async (client) => { for (const table of ['edge_observation_items','edge_observations','sale_items','sales','purchase_items','purchases','inventory','promotions','feedback','products','categories']) await client.query(`TRUNCATE TABLE ${table} RESTART IDENTITY CASCADE`); const categories = [...new Set(data.products.map((product) => product.category))]; for (const category of categories) { const slug = category.toLocaleLowerCase().replace(/[^a-z0-9]+/g, '-'); await client.query('INSERT INTO categories (id,name,slug) VALUES ($1,$2,$3)', [`category-${slug}`, category, slug]); } for (const product of data.products) { const categoryId = `category-${product.category.toLocaleLowerCase().replace(/[^a-z0-9]+/g, '-')}`; await client.query('INSERT INTO products (id,category_id,name,normalized_name,price,image_url,active) VALUES ($1,$2,$3,$4,$5,$6,TRUE)', [product.id, categoryId, product.name, product.name.toLocaleLowerCase().trim().replace(/\s+/g, ' '), product.price, product.imageUrl ?? null]); const item = data.inventory.find((candidate) => candidate.id === product.id)!; await client.query('INSERT INTO inventory (product_id,digital_stock,physical_stock,reorder_point,average_sales,last_physical_observation_at) VALUES ($1,$2,$3,$4,$5,$6)', [item.id, item.digitalStock, item.physicalStock, item.reorderPoint, item.averageSales, item.observedAt ?? null]); } for (const promotion of data.promotions) await client.query('INSERT INTO promotions (id,title,description,image_url,active) VALUES ($1,$2,$3,$4,$5)', [promotion.id, promotion.title, promotion.description, promotion.imageUrl ?? null, promotion.active]); for (const item of data.feedback) await client.query("INSERT INTO feedback (id,mood,rating,comment,created_at) VALUES ($1,$2,$3,$4,$5)", [item.id, item.mood, item.mood === 'happy' ? 5 : item.mood === 'neutral' ? 3 : 1, item.comment, item.createdAt]); }); }
}
