import { businessRepository } from '../repositories/businessRepository.js';
import { buildAlerts } from '../rules/alertEngine.js';
import { getDemandAnalytics } from './demandService.js';
import { DEMAND_OPPORTUNITY_PERIOD } from '../config/alerts.js';
import type { EdgeObservation, Feedback, InventoryRecord, PaymentMethod, ProductInput, Promotion, SaleInput } from '../types/domain.js';
import { planBudget } from '../rules/budgetPlanner.js';
import { emitOperationalEvent } from '../events/contracts.js';
import { notifyPriorityDiscrepancy } from '../integrations/twilio/whatsappAlertNotifier.js';

const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const requiredText = (value: unknown): value is string => typeof value === 'string' && value.trim().length > 0;
const positiveInteger = (value: unknown): value is number => Number.isInteger(value) && Number(value) > 0;
const validDate = (value: unknown): value is string => value === undefined || (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00.000Z`)));
export class ValidationError extends Error { public readonly statusCode = 400; }
export class NotFoundError extends Error { public readonly statusCode = 404; }

export async function getEdgeConfig() { const data = await businessRepository.read(); return { zone: 'zona-a', markers: Object.fromEntries(data.inventory.filter((item) => item.arucoId !== undefined).map((item) => [String(item.arucoId), item.id])) }; }
export async function getProducts() { return (await businessRepository.read()).products; }
export async function scanProduct(code: unknown) { if (!requiredText(code)) throw new ValidationError('El QR no contiene datos.'); const value = code.trim(); const data = await businessRepository.read(); const existing = data.products.find((product) => product.id === value || product.name.toLocaleLowerCase().trim() === value.toLocaleLowerCase()); if (existing) return { status: 'existing' as const, product: existing }; let parsed: unknown; try { parsed = JSON.parse(value); } catch { throw new ValidationError('QR no reconocido. Usa un ID de producto o un JSON con name, category, price y stock.'); } if (!parsed || typeof parsed !== 'object') throw new ValidationError('El contenido del QR no es un producto válido.'); const qrProduct = parsed as Omit<ProductInput, 'id'>; return { status: 'created' as const, product: await createProduct({ ...qrProduct, reorderPoint: typeof qrProduct.reorderPoint === 'number' ? qrProduct.reorderPoint : 0 }) }; }
export async function createProduct(input: Omit<ProductInput, 'id'>) { if (!requiredText(input.name) || !requiredText(input.category) || typeof input.price !== 'number' || !Number.isFinite(input.price) || input.price < 0 || !Number.isInteger(input.stock) || input.stock < 0 || !Number.isInteger(input.reorderPoint) || input.reorderPoint < 0 || !validDate(input.expirationDate)) throw new ValidationError('Nombre, categoría, precio, existencia, reorden y caducidad deben ser válidos.'); const data = await businessRepository.read(); if (data.products.some((product) => product.name.toLocaleLowerCase().trim() === input.name.toLocaleLowerCase().trim())) throw new ValidationError('Ya existe un producto con ese nombre.'); const idBase = input.name.toLocaleLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'producto'; return businessRepository.createProduct({ ...input, id: `${idBase}-${Date.now()}` }); }
export async function updateProduct(productId: string, input: Omit<ProductInput, 'id'>) { const data = await businessRepository.read(); if (!data.products.some((product) => product.id === productId)) throw new NotFoundError('Producto no encontrado.'); if (!requiredText(input.name) || !requiredText(input.category) || typeof input.price !== 'number' || !Number.isFinite(input.price) || input.price < 0 || !Number.isInteger(input.stock) || input.stock < 0 || !Number.isInteger(input.reorderPoint) || input.reorderPoint < 0 || !validDate(input.expirationDate)) throw new ValidationError('Nombre, categoría, precio, existencia, reorden y caducidad deben ser válidos.'); if (data.products.some((product) => product.id !== productId && product.name.toLocaleLowerCase().trim() === input.name.toLocaleLowerCase().trim())) throw new ValidationError('Ya existe un producto con ese nombre.'); return businessRepository.updateProduct(productId, { ...input, id: productId }); }
export async function getInventory() { return (await businessRepository.read()).inventory; }
export async function updateInventory(productId: string, patch: Partial<InventoryRecord>) { if (!(await businessRepository.read()).inventory.some((item) => item.id === productId)) throw new NotFoundError('Producto no encontrado.'); return businessRepository.updateInventory(productId, patch); }
export async function getSales() { return (await businessRepository.read()).sales; }
export async function registerSale(input: SaleInput) { const requestedItems = input.items ?? (requiredText(input.productId) && positiveInteger(input.quantity) ? [{ productId: input.productId, quantity: input.quantity }] : []); if (!requestedItems.length || requestedItems.some((item) => !requiredText(item.productId) || !positiveInteger(item.quantity))) throw new ValidationError('Agrega al menos un producto con una cantidad válida.'); if (input.discountTotal !== undefined && (typeof input.discountTotal !== 'number' || !Number.isFinite(input.discountTotal) || input.discountTotal < 0)) throw new ValidationError('El descuento debe ser un número mayor o igual a cero.'); const paymentMethods: PaymentMethod[] = ['cash', 'card', 'transfer']; if (input.paymentMethod !== undefined && !paymentMethods.includes(input.paymentMethod)) throw new ValidationError('Selecciona un método de pago válido.'); const data = await businessRepository.read(); const products = requestedItems.map((item) => { const product = data.inventory.find((candidate) => candidate.id === item.productId); if (!product) throw new NotFoundError(`Producto no encontrado: ${item.productId}.`); if (item.quantity > product.digitalStock) throw new ValidationError(`La cantidad de ${product.name} supera el inventario disponible.`); return product; }); const subtotal = requestedItems.reduce((sum, item, index) => sum + products[index].price * item.quantity, 0); const discountTotal = input.discountTotal ?? 0; if (discountTotal > subtotal) throw new ValidationError('El descuento no puede superar el subtotal.'); const sale = await businessRepository.registerSale({ items: requestedItems, discountTotal, paymentMethod: input.paymentMethod ?? 'cash' }); for (const item of sale.items) emitOperationalEvent({ type: 'sale.completed', timestamp: sale.createdAt, data: { saleId: sale.id, productId: item.productId, quantity: item.quantity, unitPrice: item.unitPrice, total: item.subtotal - discountTotal * (item.subtotal / subtotal) } }); return sale; }
export async function getPurchases() { return (await businessRepository.read()).purchases; }
export async function registerPurchase(input: { productId?: unknown; quantity?: unknown }) { if (!requiredText(input.productId) || !positiveInteger(input.quantity)) throw new ValidationError('Producto y cantidad válida son obligatorios.'); const productId = input.productId; const quantity = input.quantity; if (!(await businessRepository.read()).inventory.some((item) => item.id === productId)) throw new NotFoundError('Producto no encontrado.'); return businessRepository.registerPurchase(productId, quantity); }
export async function getPromotions() { return (await businessRepository.read()).promotions; }
export async function createPromotion(input: Omit<Promotion, 'id'>) { if (!requiredText(input.title) || !requiredText(input.description) || typeof input.active !== 'boolean') throw new ValidationError('La promoción no es válida.'); return businessRepository.createPromotion({ ...input, id: id('promo') }); }
export async function updatePromotion(promotionId: string, input: Partial<Promotion>) { if (!(await businessRepository.read()).promotions.some((promotion) => promotion.id === promotionId)) throw new NotFoundError('Promoción no encontrada.'); return businessRepository.updatePromotion(promotionId, input); }
export async function getFeedback() { return (await businessRepository.read()).feedback; }
export async function submitFeedback(input: Omit<Feedback, 'id'>) { if (!['sad', 'neutral', 'happy'].includes(input.mood) || typeof input.comment !== 'string' || !requiredText(input.createdAt)) throw new ValidationError('La opinión no es válida.'); const feedback = await businessRepository.submitFeedback({ ...input, id: id('feedback') }); emitOperationalEvent({ type: 'feedback.submitted', timestamp: feedback.createdAt, data: { feedbackId: feedback.id, mood: feedback.mood } }); return feedback; }
export async function getAlerts() { const data = await businessRepository.read(); const demand = await getDemandAnalytics({ period: DEMAND_OPPORTUNITY_PERIOD }); return buildAlerts(data.inventory, demand.topNotFound); }
export async function planReplenishmentBudget(input: { budget?: unknown }) { if (typeof input.budget !== 'number' || !Number.isFinite(input.budget) || input.budget <= 0) throw new ValidationError('El presupuesto debe ser un número mayor a cero.'); emitOperationalEvent({ type: 'owner.budget_available', timestamp: new Date().toISOString(), data: { budget: input.budget } }); return planBudget((await businessRepository.read()).inventory, input.budget); }
export async function notifyPriorityAlerts() {
  const data = await businessRepository.read();
  const demand = await getDemandAnalytics({ period: DEMAND_OPPORTUNITY_PERIOD });
  const alerts = buildAlerts(data.inventory, demand.topNotFound).filter((alert) => alert.severity === 'priority');
  const observedAt = new Date().toISOString();
  void Promise.allSettled(alerts.map((alert) => notifyPriorityDiscrepancy(alert, { zoneId: 'zona-a', sourceId: 'alertas-manual', observedAt })));
  return { notified: alerts.length, totalPriority: alerts.length, observedAt };
}

export async function getSummary() { const alerts = await getAlerts(); return { priority: alerts.filter((alert) => alert.severity === 'priority').length, attention: alerts.filter((alert) => alert.severity === 'attention').length, opportunity: alerts.filter((alert) => alert.severity === 'opportunity').length, stable: alerts.filter((alert) => alert.severity === 'stable').length, discrepancies: alerts.filter((alert) => alert.difference !== 0).length, reorder: alerts.filter((alert) => alert.digitalStock <= alert.reorderPoint).length }; }
export async function ingestObservation(observation: EdgeObservation) {
  if (!requiredText(observation.zoneId) || !requiredText(observation.sourceId) || !requiredText(observation.timestamp) || !Array.isArray(observation.items) || observation.items.length === 0) throw new ValidationError('La observación Edge no es válida.');
  for (const item of observation.items) if (!requiredText(item.productId) || !Number.isInteger(item.quantity) || item.quantity < 0) throw new ValidationError('Cada item Edge requiere producto y quantity no negativa.');
  const current = await businessRepository.read(); const observationId = observation.observationId?.trim() || `observation-${Date.now()}`; const duplicate = current.processedObservationIds.includes(observationId);
  for (const entry of observation.items) if (!current.inventory.some((item) => item.id === entry.productId)) throw new NotFoundError(`Producto no encontrado: ${entry.productId}.`);
  const next = duplicate ? current : await businessRepository.ingestObservation({ observationId, zoneId: observation.zoneId, sourceId: observation.sourceId, observedAt: observation.timestamp, items: observation.items });
  const demand = await getDemandAnalytics({ period: DEMAND_OPPORTUNITY_PERIOD });
  for (const item of observation.items) emitOperationalEvent({ type: 'stock.physical_observed', timestamp: observation.timestamp, data: { zoneId: observation.zoneId, sourceId: observation.sourceId, productId: item.productId, quantity: item.quantity, observedAt: observation.timestamp } });
  const alerts = buildAlerts(next.inventory, demand.topNotFound);
  if (!duplicate) {
    await Promise.all(observation.items.map(async (item) => {
      const alert = alerts.find((candidate) => candidate.productId === item.productId && candidate.severity === 'priority');
      if (alert) await notifyPriorityDiscrepancy(alert, { zoneId: observation.zoneId, sourceId: observation.sourceId, observedAt: observation.timestamp });
    }));
  }
  return { observationId, duplicate, observedAt: observation.timestamp, inventory: next.inventory, alerts };
}
