import { useCallback, useEffect, useRef, useState } from 'react';
import { cancelSpeech, canUseSpeechSynthesis, createSpeechUtterance, getSpeechVoices, subscribeToVoicesChanged } from './voice/speechSynthesis';
import { createSpeechRecognition, getSpeechRecognitionConstructor } from './voice/speechRecognition';
import type { SpeechRecognitionLike, VoiceStatus } from './voice/types';
function friendlyError(error?: string) { switch (error) { case 'no-speech': return 'No escuché ninguna pregunta. Intenta nuevamente.'; case 'audio-capture': return 'Brave no detectó un micrófono disponible.'; case 'not-allowed': case 'service-not-allowed': return 'Brave bloqueó el acceso al micrófono. Revisa el permiso de localhost.'; case 'network': return 'Brave capturó el micrófono, pero no pudo conectar su servicio de reconocimiento. Prueba Chrome o activa el reconocimiento local.'; case 'language-not-supported': return 'El navegador no tiene reconocimiento local para español. Prueba Chrome o escribe la pregunta.'; case 'aborted': return ''; default: return 'No pude usar el reconocimiento de voz. También puedes escribir.'; } }
export function useCustomerVoice(onTranscript: (transcript: string) => void) { const recognitionRef = useRef<SpeechRecognitionLike>(); const recognitionGenerationRef = useRef(0); const currentUtteranceRef = useRef<SpeechSynthesisUtterance | null>(null); const speechGenerationRef = useRef(0); const transcriptRef = useRef(onTranscript); const mountedRef = useRef(true); const [status, setStatus] = useState<VoiceStatus>('unsupported'); const [error, setError] = useState(''); const canSpeak = canUseSpeechSynthesis(); transcriptRef.current = onTranscript;
  useEffect(() => { mountedRef.current = true; setStatus(getSpeechRecognitionConstructor() ? 'idle' : 'unsupported'); const removeVoicesListener = subscribeToVoicesChanged(() => { if (import.meta.env.DEV) console.debug('[customer-voice] voiceschanged', { voicesCount: getSpeechVoices().length }); }); return () => { mountedRef.current = false; recognitionGenerationRef.current += 1; recognitionRef.current?.abort(); recognitionRef.current = undefined; speechGenerationRef.current += 1; currentUtteranceRef.current = null; cancelSpeech(); removeVoicesListener(); }; }, []);
  const startListening = useCallback(() => { if (recognitionRef.current || !getSpeechRecognitionConstructor()) return; speechGenerationRef.current += 1; currentUtteranceRef.current = null; cancelSpeech(); setError(''); const generation = ++recognitionGenerationRef.current; const recognition = createSpeechRecognition({ onFinal: (transcript) => { if (generation === recognitionGenerationRef.current && mountedRef.current) transcriptRef.current(transcript.trim()); }, onError: (code) => { if (import.meta.env.DEV) console.warn('[customer-voice] recognition error', code); if (generation === recognitionGenerationRef.current) { recognitionRef.current = undefined; if (mountedRef.current) { setStatus('idle'); setError(friendlyError(code)); } } }, onEnd: () => { if (generation === recognitionGenerationRef.current) { recognitionRef.current = undefined; if (mountedRef.current) setStatus('idle'); } } }); if (!recognition) { setStatus('unsupported'); return; } recognitionRef.current = recognition; try { recognition.start(); setStatus('listening'); } catch { recognitionRef.current = undefined; setStatus('idle'); setError('No pude iniciar el micrófono. También puedes escribir.'); } }, []);
  const stopListening = useCallback(() => { const recognition = recognitionRef.current; if (!recognition) return; try { recognition.stop(); } catch { recognition.abort(); } }, []);
  const speak = useCallback((text: string) => { if (!text.trim() || !canUseSpeechSynthesis()) return; const recognition = recognitionRef.current; if (recognition) { try { recognition.abort(); } catch { /* ya terminó */ } recognitionRef.current = undefined; recognitionGenerationRef.current += 1; } const generation = ++speechGenerationRef.current; currentUtteranceRef.current = null; cancelSpeech(); setError(''); const utterance = createSpeechUtterance(text); currentUtteranceRef.current = utterance; utterance.onstart = () => { if (generation === speechGenerationRef.current && mountedRef.current) setStatus('speaking'); }; utterance.onend = () => { if (generation === speechGenerationRef.current) { currentUtteranceRef.current = null; if (mountedRef.current) setStatus('idle'); } }; utterance.onerror = (event) => { if (generation !== speechGenerationRef.current || event.error === 'canceled' || event.error === 'interrupted') return; if (import.meta.env.DEV) console.warn('[customer-voice] synthesis error', event.error); currentUtteranceRef.current = null; if (mountedRef.current) { setStatus('idle'); setError('Brave no pudo reproducir la respuesta. Revisa el audio del navegador o prueba Chrome.'); } }; window.setTimeout(() => { if (generation === speechGenerationRef.current && currentUtteranceRef.current === utterance && canUseSpeechSynthesis()) window.speechSynthesis.speak(utterance); }, 0); }, []);
  const stopSpeaking = useCallback(() => { speechGenerationRef.current += 1; currentUtteranceRef.current = null; cancelSpeech(); if (mountedRef.current) setStatus((current) => current === 'speaking' ? 'idle' : current); }, []);
  return { status, error, canListen: Boolean(getSpeechRecognitionConstructor()), canSpeak, startListening, stopListening, speak, stopSpeaking };
}
